name: Pre-Commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies from all services
        run: |
          pip install -r meeting-service/requirements.txt
          pip install -r user-service/requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files
