name: Multi-Service Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.11'

jobs:
  test-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - meeting-service
          - user-service
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    env:
      PYTHONPATH: ${{ github.workspace }}/${{ matrix.service }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Run tests with coverage
      run: pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: ${{ matrix.service }}-unittests
        name: codecov-umbrella
        fail_ci_if_error: true
